[package]
name = "mp4"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.25"
auto_impl = "0.3.0"
byteorder = "1.3.2"
byte_struct = "0.6.0"
byte_struct_derive = "0.4.2"
chrono = "0.4.10"
